---
title: "R Notebook - color study <br> written by Hyojin Kim"
output: html_notebook
---


```{r}

# call library 
require(dplyr)
library(tidyr)
library(reshape2)
library(ggplot2)
library(furrr)
library(tibble)
library(purrr)
library(reticulate)
library(viridis)
library(ggrepel)
library(patchwork)
library(ggridges)
library(ggpubr)
library(gtools)
library(RColorBrewer)
library(scales)

#indir = "~/singlecellRNA-seq_2022/color_study/data/"
D <- read.table(paste0(indir, "example.txt"), sep = "\t", header = TRUE)

```

```{r}
head(D)
```

```{r}
getPalette = colorRampPalette(brewer.pal(8, "Accent")) 

group <- factor(D$group, levels=sort(unique(D$group)))
colourSet = setNames(getPalette(length(levels(group))), levels(group))
colourSet
```


```{r}
show_col(colourSet)
```

```{r}
p <- ggplot(D, aes(x=x, y=y, color=group) ) +
                  scale_color_manual(values=colourSet) +
                  geom_point(size=1, alpha=0.6) +
                  labs(title = "Accent") +        
                  theme_classic()


print(p)
```

```{r}
getPalette = colorRampPalette(brewer.pal(8, "Set1")) 

group <- factor(D$group, levels=sort(unique(D$group)))
colourSet = setNames(getPalette(length(levels(group))), levels(group))
colourSet
```

```{r}
show_col(colourSet)
```

```{r}
p <- ggplot(D, aes(x=x, y=y, color=group) ) +
                  scale_color_manual(values=colourSet) +
                  geom_point(size=1, alpha=0.6) +
                  labs(title = "Set1") +
                  theme_classic() 


print(p)
```

```{r}
getPalette = colorRampPalette(brewer.pal(8, "Set2")) 

group <- factor(D$group, levels=sort(unique(D$group)))
colourSet = setNames(getPalette(length(levels(group))), levels(group))
colourSet
```

```{r}
show_col(colourSet)
```

```{r}
p <- ggplot(D, aes(x=x, y=y, color=group) ) +
                  scale_color_manual(values=colourSet) +
                  geom_point(size=1, alpha=0.8) +
                  labs(title = "Set2") +
                  theme_classic()  

print(p)
```
```{r}
getPalette = colorRampPalette(brewer.pal(8, "Set3")) 

group <- factor(D$group, levels=sort(unique(D$group)))
colourSet = setNames(getPalette(length(levels(group))), levels(group))
colourSet
```
```{r}
show_col(colourSet)
```
```{r}
p <- ggplot(D, aes(x=x, y=y, color=group) ) +
                  scale_color_manual(values=colourSet) +
                  geom_point(size=1, alpha=0.8) +
                  labs(title = "Set3") +
                  theme_classic()  

print(p)
```

```{r}
# Shuffle colors of set2
getPalette = colorRampPalette(brewer.pal(8, "Set2")) 
L <- sort(unique(D$group))
L <- L[sample(1:length(L))]
group <- factor(D$group, levels=sort(unique(D$group)))
colourSet = setNames(getPalette(length(levels(group))), L)
colourSet <- colourSet[sort(unique(D$group))]
colourSet
```

```{r}
show_col(colourSet)
```

```{r}
p <- ggplot(D, aes(x=x, y=y, color=group) ) +
                  scale_color_manual(values=colourSet) +
                  geom_point(size=1, alpha=0.6) +
                  labs(title = "Set2_shuffling") +
                  theme_classic()  

print(p)
```


```{r}
sessionInfo()
```

